
FROM python:3.9-slim

WORKDIR /app

COPY . /app

COPY Apellidos.xlsx /app/  
COPY Nombres_Edades.xlsx /app/

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir fastapi uvicorn pandas faker openpyxl


EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
